package antexpert;


import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.HashMap;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cepheus
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public String componentLabel="";
    public String components = "";
    public DefaultListModel<String> defaultListModel;
    public DefaultListModel<String> defaultListModel_orglabels;
    
    public String createDirectoryName = "";
    
    public List<String> metadatalist;
    
    public static String SELECTED_ORG_LABEL;
    public static final String newChangeLineComment = "<!--new changes here-->\n";
    public static float VERSION = 41.0f;
    public static final String head = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Package xmlns=\"http://soap.sforce.com/2006/04/metadata\">\n";
    public static final String version = "<version>" + VERSION + "</version>\n";
    public static final String tail = "</Package>\n";
    
    public static final String base_path = FileSystems.getDefault().getPath("").toAbsolutePath().toString();
    
    //Package members
    public static String packageString = "";
    public Map<String, String[]> metadata_map;
    public Map<String, MdUtility> org_map;
    
    //folder maps
    String retreive = "\\Ant\\retreive";
    String old_pkg = "\\Ant\\old_packages";
    String config = "\\Ant\\config";
    String build_prop = "\\Ant\\build.properties";
         
        
    public NewJFrame() {
        
        initComponents();
        
        init();
       
    }
    
     private void init() {
        jList_oldpackage_names.setVisible(false);
        jLabel_added.setVisible(false);
        jButton_add.setVisible(false);
       
        jPopupMenu.add(jPanel1);
        
        metadata_map = new HashMap<String, String[]>();
        org_map = new HashMap<String, MdUtility>();
        
        jTextField_newpackage_name.setText( "package.xml");
        
        
        MdUtility mdUtility = new MdUtility();
        metadatalist = Arrays.asList( mdUtility.metadata_list.split("\n"));
        
        defaultListModel = new DefaultListModel<>();
        jList_metadata_types.setModel(defaultListModel);
        
        defaultListModel_orglabels = new DefaultListModel<>();
        jList_orgLabels.setModel(defaultListModel_orglabels);
        
        createFolderMap();
          
    }
     
     private void createFolderMap(){
        
        
         File file = new File(base_path+retreive);
         if(  !file.isDirectory()){
             file.mkdirs();
         }
         
         file = new File(base_path+old_pkg);
         if(  !file.isDirectory()){
             file.mkdirs();
         }
         
         try{
            file = new File(base_path+config);
            if( !file.exists()){
               file.createNewFile();
            }else{
                String line;
                BufferedReader br = new BufferedReader(new FileReader(file));
                while ((line = br.readLine()) != null) {
                    String[] arr = line.split("\t");
                    defaultListModel_orglabels.addElement(arr[0]);
                    org_map.put( arr[0], new MdUtility(arr[0], arr[1], arr[2], arr[3], arr[4]));
                } 
            }
         }catch(IOException ex){
             ex.printStackTrace();
         }
                  
     }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_metadata_types = new javax.swing.JList<>();
        jPopupMenu = new javax.swing.JPopupMenu();
        buttonGroup_pkgaction = new javax.swing.ButtonGroup();
        jPanel_pkg_details = new javax.swing.JPanel();
        jButton_add = new javax.swing.JButton();
        jButton_preview = new javax.swing.JButton();
        jLabel_added = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton_save = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_oldpackage_names = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_components = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jTextField_metadata = new javax.swing.JTextField();
        jTextField_newpackage_name = new javax.swing.JTextField();
        jButton_backup_packages = new javax.swing.JButton();
        jPanel3_org_details = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_orgLabels = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel_urltype = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_maxpoll = new javax.swing.JLabel();
        jButton_addOrg = new javax.swing.JButton();
        jButton_selectorg = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jList_metadata_types.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_metadata_typesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_metadata_types);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPopupMenu.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_pkg_details.setBorder(javax.swing.BorderFactory.createTitledBorder("Create/ Update Package"));

        jButton_add.setText("Add  \nComponents");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_preview.setText("Preview Components");
        jButton_preview.setEnabled(false);
        jButton_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_previewActionPerformed(evt);
            }
        });

        jLabel_added.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_added.setForeground(new java.awt.Color(24, 219, 23));
        jLabel_added.setText("Added");

        buttonGroup_pkgaction.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("create");
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup_pkgaction.add(jRadioButton2);
        jRadioButton2.setText("update");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton_save.setText("Save");
        jButton_save.setEnabled(false);
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jList_oldpackage_names.setBorder(javax.swing.BorderFactory.createTitledBorder("select package to update"));
        jList_oldpackage_names.setToolTipText("");
        jScrollPane3.setViewportView(jList_oldpackage_names);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Components"));

        jTextArea_components.setColumns(20);
        jTextArea_components.setRows(5);
        jTextArea_components.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea_componentsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_components);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("select metadata"));

        jTextField_metadata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_metadataKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField_metadata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTextField_metadata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton_backup_packages.setText("BACKUP");

        javax.swing.GroupLayout jPanel_pkg_detailsLayout = new javax.swing.GroupLayout(jPanel_pkg_details);
        jPanel_pkg_details.setLayout(jPanel_pkg_detailsLayout);
        jPanel_pkg_detailsLayout.setHorizontalGroup(
            jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_added))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_newpackage_name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_backup_packages))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_preview)))
                .addGap(25, 25, 25))
            .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                .addGap(571, 571, 571)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel_pkg_detailsLayout.setVerticalGroup(
            jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pkg_detailsLayout.createSequentialGroup()
                .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jTextField_newpackage_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_add)
                            .addComponent(jButton_backup_packages))))
                .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_save)
                            .addComponent(jButton_preview))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel_pkg_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_added)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel_pkg_detailsLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel3_org_details.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Organization "));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel6.setText("select org name");

        jList_orgLabels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_orgLabelsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList_orgLabels);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("sf.serverurl");

        jLabel_urltype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_urltype.setText("server url name");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("sf.maxpoll");

        jLabel_maxpoll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_maxpoll.setText("maxpoll");

        jButton_addOrg.setText("Add New Org Cred.");
        jButton_addOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addOrgActionPerformed(evt);
            }
        });

        jButton_selectorg.setText("Select org.");
        jButton_selectorg.setEnabled(false);
        jButton_selectorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectorgActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3_org_detailsLayout = new javax.swing.GroupLayout(jPanel3_org_details);
        jPanel3_org_details.setLayout(jPanel3_org_detailsLayout);
        jPanel3_org_detailsLayout.setHorizontalGroup(
            jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_addOrg))
                    .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                                .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel_urltype, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel_maxpoll)))
                            .addComponent(jButton_selectorg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3_org_detailsLayout.setVerticalGroup(
            jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                                .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3_org_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel_maxpoll))
                                        .addGroup(jPanel3_org_detailsLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel_urltype)))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_selectorg))))
                    .addComponent(jButton_addOrg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Deploy/ Retreive Package"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deploy", "Retreive" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_pkg_details, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3_org_details, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3_org_details, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_pkg_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        components = jTextArea_components.getText().toString();
        
        String [] arr = formatComponents(components);
        metadata_map.put( jTextField_metadata.getText().toString() , arr);      
        
        jLabel_added.setVisible(true);
        
        jButton_save.setEnabled(true);
        jButton_preview.setEnabled(true);
    }//GEN-LAST:event_jButton_addActionPerformed

    public static String[] formatComponents(String cmp){
       
        boolean isTabSeparated = cmp.contains("\t");
        boolean isCommaSeparated = cmp.contains(",");
        boolean isSpaceSeparated = cmp.contains(" ");
        boolean isNewLineSeparated = cmp.contains("\n");
        
        String[] arr = new String[1];

        if(isTabSeparated){
            // System.out.println("Tab separated");
            arr = cmp.split("\t");
        }else if(isSpaceSeparated){
            // System.out.println("Space separated");
            arr = cmp.split(" ");
        }else if(isCommaSeparated){
            // System.out.println("Comma separated");
            arr = cmp.split(",");
        }else if(isNewLineSeparated){
            arr = cmp.split("\n");
        }else{
            arr[0] = cmp;
        }
        
        return arr;
    }
    
    private void jTextField_metadataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_metadataKeyReleased
        // TODO add your handling code here:

        
        if(evt.getKeyCode() == evt.VK_ENTER){
            jTextField_metadata.setText( jList_metadata_types.getSelectedValue() );
        }
        
        String metadata =  jTextField_metadata.getText().trim().toLowerCase();
        
        if(!metadata.equals("")){
            
            jLabel_added.setVisible(false);
            
            
            defaultListModel.removeAllElements();
            
            for(String m : metadatalist){
                if(m.toLowerCase().contains(metadata))
                    defaultListModel.addElement(m);
            }
            jList_metadata_types.setSelectedIndex(0);
            jPopupMenu.show(jTextField_metadata, 0 , jTextField_metadata.getHeight());
      
        }

    }//GEN-LAST:event_jTextField_metadataKeyReleased
    
    
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jList_oldpackage_names.setVisible(false);
        jTextField_newpackage_name.setVisible(true);
        
        createDirectoryName = new SimpleDateFormat("yyyy/MM/dd_HH:mm:ss").format(new Date());
        
        jTextField_newpackage_name.setText( "package.xml");
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jTextField_newpackage_name.setVisible(false);
        jList_oldpackage_names.setVisible(true);

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jList_metadata_typesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_metadata_typesMouseClicked
        // TODO add your handling code here:
        jTextField_metadata.setText(jList_metadata_types.getSelectedValue());
    }//GEN-LAST:event_jList_metadata_typesMouseClicked

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        packageString = createPackageString(metadata_map);
        
        // save to directory
        try{
            BufferedWriter bf = new BufferedWriter( new FileWriter(new File(base_path + retreive +"\\" + jTextField_newpackage_name.getText() )));
            bf.write(packageString);
            bf.close();
        }catch(IOException ex){
            ex.printStackTrace();
        }
        
        JOptionPane.showMessageDialog( new JFrame(),"Package has been saved.\nBegin creating new package."); 
        
        jButton_preview.setEnabled(false);
        
        //reset
        metadata_map = new HashMap<>();
        jTextArea_components.setText("");
        jTextField_metadata.setText("");
        
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jTextArea_componentsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_componentsKeyReleased
        // TODO add your handling code here:
        components = jTextArea_components.getText().toString();
        
        if(!components.equals("")){
            
            jButton_add.setVisible(true);
                     
        }else{
            jButton_add.setVisible(false);
            
        } 
        
    }//GEN-LAST:event_jTextArea_componentsKeyReleased

    private void jButton_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_previewActionPerformed
        // TODO add your handling code here:
        
        StringBuilder sb = new StringBuilder();
        sb.append(head);

        for(Map.Entry<String, String[]> entry : metadata_map.entrySet() ){
            
            sb.append("<types>\n");
            String key_name = entry.getKey();
            String [] value_members = entry.getValue();

            if(value_members.length > 0){
                
                for(String member: value_members){
                    if(!member.equals(""))
                        sb.append("\t<members>"+member+"</members>\n");
                }
            }   
            sb.append("\t<name>"+key_name+"</name>\n</types>\n\n");    
        }
        
        sb.append(version);
        sb.append(tail);
        
        //pop up display
        JTextArea textArea = new JTextArea(sb.toString());
        JScrollPane scrollPane = new JScrollPane(textArea);  
        textArea.setLineWrap(true);  
        textArea.setWrapStyleWord(true); 
        scrollPane.setPreferredSize( new Dimension( 500, 500 ) );
        JOptionPane.showMessageDialog(null, scrollPane, "Preview Components List",  
                                               JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jButton_previewActionPerformed

    private void jButton_addOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addOrgActionPerformed
        // TODO add your handling code here:
        
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(0, 2, 2, 2));

        JTextField username = new JTextField(10);
        JTextField password = new JTextField(10);
        JTextField maxpoll = new JTextField(10);
        maxpoll.setText("20");
        JTextField label = new JTextField(10);
        
        ButtonGroup group = new ButtonGroup();
        JRadioButton test_org = new JRadioButton();
        test_org.setText("test");
        test_org.setSelected(true);
        JRadioButton login_org = new JRadioButton();
        login_org.setText("login");
        group.add(test_org);
        group.add(login_org);
        
        panel.add(new JLabel("Label  : "));
        panel.add(label);
        panel.add(new JLabel("username : "));
        panel.add(username);
        panel.add(new JLabel("password : "));
        panel.add(password);
        panel.add(new JLabel("maxpoll : "));
        panel.add(maxpoll);
        panel.add(new JLabel("Select servel url "));
        panel.add(new JLabel("(Sanbox / production): "));
        panel.add(test_org);
        panel.add(login_org);
        
        
        int option =JOptionPane.showConfirmDialog(new JFrame(),
                                                    panel,
                                                    "Add credentials here.",
                                                    JOptionPane.OK_CANCEL_OPTION,
                                                    JOptionPane.INFORMATION_MESSAGE);
        // add security token
        // add null check for username and password
        if(option == JOptionPane.OK_OPTION && !org_map.containsKey(label.getText()) && !label.getText().isEmpty() ){
  
            String l, u, p, m, tg;
            l = label.getText();
            u = username.getText();
            p = password.getText();
            m = maxpoll.getText();
            tg = test_org.isSelected()? "test" : "login";
            
            org_map.put(l, new MdUtility( l, u, p, m,tg) );
            
            try{
               BufferedWriter bw = new BufferedWriter(new FileWriter(base_path + config, true));
               //label username password maxpoll tg
               bw.write(l+"\t"+u+"\t"+p+"\t"+m+"\t"+tg+"\n");
               bw.close();
            }catch(IOException ex){
                ex.printStackTrace();
            }
           
            defaultListModel_orglabels.addElement(l);
            
        }else if( label.getText().isEmpty() && option == JOptionPane.OK_OPTION ){
            JOptionPane.showMessageDialog(this, "Label cannot be empty.");                
        }else if( org_map.containsKey(label.getText()) ){
            JOptionPane.showMessageDialog(this, "An Org exists with the same label !! Try Another.");
        }
        
    }//GEN-LAST:event_jButton_addOrgActionPerformed

    private void jList_orgLabelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_orgLabelsMouseClicked
        // TODO add your handling code here:
        MdUtility mdUtility = org_map.get( jList_orgLabels.getSelectedValue() );
        jLabel_urltype.setText( mdUtility.getOrg_type());
        jLabel_maxpoll.setText( mdUtility.getMaxpoll());
        
        jButton_selectorg.setEnabled(true);
    }//GEN-LAST:event_jList_orgLabelsMouseClicked

    private void jButton_selectorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectorgActionPerformed
        // TODO add your handling code here:
        
        SELECTED_ORG_LABEL = jList_orgLabels.getSelectedValue();
        // make build file
        String buildP_string = org_map.get(SELECTED_ORG_LABEL).getBuildProperties();

        try{
            BufferedWriter bw = new BufferedWriter(new FileWriter(new File(base_path + build_prop)));
            bw.write(buildP_string);
            bw.close();
        }catch(IOException ex){
            ex.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(this, SELECTED_ORG_LABEL +" <- credentials have been selected.\nDeployment"
                + " and retreival will happen through these. ");
    }//GEN-LAST:event_jButton_selectorgActionPerformed
    
     
    public static String createPackageString(Map<String, String[]> allcomp){

        StringBuilder sb = new StringBuilder();
        sb.append(head);

        for(Map.Entry<String, String[]> entry : allcomp.entrySet() ){
            
            sb.append("<types>\n");
            String key_name = entry.getKey();
            String [] value_members = entry.getValue();

            if(value_members.length > 0){
                
                for(String member: value_members){
                    if(!member.equals(""))
                        sb.append("\t<members>"+member+"</members>\n");
                }
            }   
            sb.append("\t<name>"+key_name+"</name>\n</types>\n\n");    
        }
        
        sb.append(version);
        sb.append(tail);

        return new String(sb);

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_pkgaction;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_addOrg;
    private javax.swing.JButton jButton_backup_packages;
    private javax.swing.JButton jButton_preview;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_selectorg;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_added;
    private javax.swing.JLabel jLabel_maxpoll;
    private javax.swing.JLabel jLabel_urltype;
    private javax.swing.JList<String> jList_metadata_types;
    private javax.swing.JList<String> jList_oldpackage_names;
    private javax.swing.JList<String> jList_orgLabels;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3_org_details;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_pkg_details;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_components;
    private javax.swing.JTextField jTextField_metadata;
    private javax.swing.JTextField jTextField_newpackage_name;
    // End of variables declaration//GEN-END:variables

   
}
